### ISSUE TITLE
Bug#1:Card内无法使用overflow-y:scroll以及width

### ISSUE THREAD

**Issue by chihuo2104** [chihuo2104/chiweb#1]
结果：会被截断并且无法使用

该问题没有啥好解决方案，暂时无法解决www

可能是对Grid不太好的技术www

**Comment by chihuo2104** [comment]
# 这个问题暂时还没啥好解法....
求助dalao:@so1ve

**Comment by chihuo2104** [comment]
要测试请把一堆`<br>`的注释取消掉之后就知道什么问题了www

**Comment by so1ve** [comment]
好家伙 我明天康康

**Comment by chihuo2104** [comment]
新版还是有这个问题 qwq

**Comment by chihuo2104** [comment]
问题解决！用fixed就行啦
![GIF 2021-12-26 11-24-16](https://user-images.githubusercontent.com/38580503/147398128-1e5fc658-9d2c-4e9e-b51e-3887f7a0dfdc.gif)
