### ISSUE TITLE
Bug#2: flex-grow无效

### ISSUE THREAD

**Issue by chihuo2104** [chihuo2104/chiweb#2]
结果：如此所见
![errorno2](https://user-images.githubusercontent.com/38580503/147398157-214366d9-012a-402e-b123-1cc51e80ce40.png)
理论上友情链接和个人网站应该一样大
已经都设置了`flex-grow:2`

**Comment by chihuo2104** [comment]
求助大佬:@so1ve

**Comment by chihuo2104** [comment]
v4版本已重写 此issue无效。

**Comment by so1ve** [comment]
（x 什么古老issue
@chihuo2104
